# Generated by Django 4.1.3 on 2022-12-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appoiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('DoctorName', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('Hours', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=10)),
                ('FirstMiddle', models.CharField(max_length=10)),
                ('FirstLast', models.CharField(max_length=10)),
                ('Email', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('idm', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=10)),
                ('FirstMiddle', models.CharField(max_length=10)),
                ('FirstLast', models.CharField(max_length=10)),
                ('Email', models.IntegerField(max_length=20)),
                ('BirthDate', models.DateField()),
                ('Gender', models.IntegerField(max_length=8)),
                ('Password', models.IntegerField(max_length=20)),
            ],
        ),
    ]
