# Generated by Django 4.1.3 on 2022-12-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Email',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Email',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Gender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Password',
            field=models.IntegerField(),
        ),
    ]
