# Generated by Django 4.1.3 on 2022-12-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctors_email_alter_patient_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EducationsLiences', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InsertAppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfAppoiment', models.DateField()),
                ('LocationOfAppoiment', models.CharField(max_length=30)),
                ('HoursOfWork', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40)),
                ('Age', models.TextField(max_length=300)),
                ('WhatBefor', models.CharField(max_length=255)),
                ('WhatAfter', models.CharField(max_length=255)),
                ('WhatToDo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bahri', models.CharField(max_length=100000)),
                ('Khartoum', models.CharField(max_length=100000)),
                ('OmDurman', models.CharField(max_length=100000)),
            ],
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='FirstLast',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='FirstMiddle',
            new_name='MiddleName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='FirstLast',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='FirstMiddle',
            new_name='MiddleName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Gender',
            new_name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Password',
        ),
    ]
