# Generated by Django 4.1.3 on 2023-01-02 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorinfo_insertappo_vaccine_vaccinelocations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='doctor.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='doctor.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Appoiments',
        ),
    ]
