# Generated by Django 4.1.3 on 2023-01-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_reservations_delete_appoiments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertappo',
            name='DateOfAppoiment',
            field=models.DateTimeField(),
        ),
    ]
