# Generated by Django 4.1.3 on 2023-01-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_insertappo_dateofappoiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Email',
            field=models.CharField(max_length=100),
        ),
    ]
