# Generated by Django 4.1.3 on 2023-01-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='DateOfBirth',
            field=models.DateTimeField(default=True),
        ),
    ]
