# Generated by Django 4.1.3 on 2023-01-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_doctors_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='DateOfBirth',
            field=models.DateTimeField(max_length=10),
        ),
    ]
