# Generated by Django 4.1.3 on 2023-01-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_alter_doctors_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='DateOfBirth',
        ),
    ]
