# Generated by Django 4.1.3 on 2023-01-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_remove_doctors_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='BirthDate',
        ),
    ]
