# Generated by Django 4.1.3 on 2023-01-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_remove_patient_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insertappo',
            name='DateOfAppoiment',
        ),
    ]
