# Generated by Django 4.1.3 on 2023-01-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_remove_insertappo_dateofappoiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40)),
                ('Age', models.TextField(max_length=300)),
                ('Description', models.CharField(max_length=255)),
                ('WhatBefor', models.CharField(max_length=255)),
                ('WhatAfter', models.CharField(max_length=255)),
                ('WhatToDo', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='VaccineLocations',
            new_name='VaccinationLocations',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
