# Generated by Django 4.1.3 on 2023-01-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_vaccinations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinations',
            name='Description',
        ),
    ]
