# Generated by Django 4.1.3 on 2023-01-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_remove_vaccinations_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vaccinations',
            new_name='Vaccine',
        ),
        migrations.RenameModel(
            old_name='VaccinationLocations',
            new_name='VaccineLocations',
        ),
    ]
