# Generated by Django 4.1.3 on 2023-01-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_rename_vaccinations_vaccine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='Day',
            field=models.DateField(default=2),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Email',
            field=models.CharField(max_length=19),
        ),
    ]
