# Generated by Django 4.1.3 on 2023-01-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_reservations_day_alter_doctors_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='Day',
            field=models.DateField(verbose_name='XYZ Date'),
        ),
    ]
